### ISSUE TITLE
Henrique Rosa - 11.02741-0 - 25/05/2016 - Completa

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [NSEE/LPKF#10]
# Sobre :
- Nome do Aluno : Henrique Pereira Rosa
- R.A : 11.02741-0
- Habilitação : Engenharia Eletrônica
- Ano : 2016
- Nome do Orientador: Rafafel Corsi 
- Nome do Projeto : BLDC-Hardware
# PCB :
- Nome da Placa : BLDC.PcbDoc
- Link para arquivos :  https://drive.google.com/open?id=0B0FWPGMv9ogrX3NvRWdKZXpQTUU
## Informações básicas
- Pequeno descritivo sobre a placa :
- Software utilizado 
  - [x] Altium
  - [ ] Eagle
  - [ ] Orcad
  - [ ] UltiBoard
  - [ ] Outro
- Tipo de prototipagem
  - [ ] Simples
  - [x] Completa
- Descrição :
  - [ ] Face Simples
  - [x] Dupla Face
  - [x] SMD
  - [ ] Trilha RF
  - [x] Máscara

**Comment by EvertonFracaroli** [comment]
Boa Tarde @HenriquePereiraRosa, você poderia indicar o caminho exato dos arquivos.

**Comment by EvertonFracaroli** [comment]
autorizado pelo Corsi via telefone

**Comment by HenriquePereiraRosa** [comment]
Boa terde @EvertonFracaroli.

Corrigido: https://drive.google.com/open?id=0B0FWPGMv9ogrX3NvRWdKZXpQTUU

**Comment by EvertonFracaroli** [comment]
Boa Tarde @HenriquePereiraRosa , vou ver com o @corsiferrao as extensões do seu arquivo, aqui no meu software esta dando alguns conflitos.

**Comment by HenriquePereiraRosa** [comment]
@EvertonFracaroli 
OK! Qualquer coisa eu posso gerá-los junto com você aí na Mauá. Porque várias opções de exportação no Altium e as vezes é necessária alguma específica.
Para adiantar vou atualizar os gerbers gerar algumas outras extensões.

Qualquer novidade estou à disposição.

**Comment by HenriquePereiraRosa** [comment]
Bom dia @EvertonFracaroli!

Abri o no Gerbv e realmente erro, porém em "Files >> Open layer(s)..." apresenta erro mas abre.
De qualquer gerei novamente os gerbers mesmo eles já estando de acordo com o guia Micropress.

Qualquer novidade é só me avisar.

**Comment by EvertonFracaroli** [comment]
Obrigado @HenriquePereiraRosa , vou verificar.

**Comment by EvertonFracaroli** [comment]
@HenriquePereiraRosa  e @corsiferrao, aparentemente esta tudo certo, agora vou fazer a placa e ver como vai ficar.

Obrigado

**Comment by rafaelcorsi** [comment]
@HenriquePereiraRosa  estamos corrigindo um problema na câmera de vídeo da LPKF que é utilizada no processo de fabricação de PCBs dupla face, pode ser que não conseguimos entregar no prazo especificado. 

Mantemos vocês informados.
