### ISSUE TITLE
Lucas Ribeiro - 14.03097-7 - 24/10/2017 - Simples

### ISSUE THREAD

**Issue by VagnerPossatoJunior** [NSEE/LPKF#101]
# Sobre :

- Nome do Aluno : Lucas Ribeiro Gomes
- R.A : 14.03097-7
- Habilitação : CA
- Ano : 2017
- Nome do Orientador: Alessandra
- Nome do Projeto : Esteira Separadora
- Nome da Disciplina  : Eletrônica Analógica / Digital

# PCB :

- Nome da Placa : Esteira
- Link para arquivos : https://drive.google.com/open?id=0ByC9Re_9F7YKb0NhRk1tZUx3d00

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X ) Simples
 - ( ) Completa

- Descrição :
 - ( X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa tarde Lucas.
Sua Placa está Pronta
Renato
