### ISSUE TITLE
Nemer C. - 15.03515-8 - 27/10/17 - Simples

### ISSUE THREAD

**Issue by nemerchiedde** [NSEE/LPKF#103]
# Sobre :

- Nome do Aluno :  Nemer Chiedde
- R.A : 15.03515-8
- Habilitação :  Elétrica
- Ano : 3 ano
- Nome do Orientador: Sergio 
- Nome do Projeto : Placa Fonte
- Nome da Disciplina  : PAE - ET3001 - Projetos eletrônicos 1

# PCB :

- Nome da Placa : Placa Fonte
- Link para arquivos : https://www.dropbox.com/s/bx2y6e7ivojbaf3/fonte.zip?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa : 
Fonte de 12V, 5V e 3V3

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by nemerchiedde** [comment]
Olá,
O link que havia colocado estava incorreto, já atualizei. 
Obrigado desde já,

Nemer.

**Comment by Renatolab** [comment]
Boa noite Nemer
Sua Placa está pronta
Renato
