### ISSUE TITLE
Eletrônica digital e analogica

### ISSUE THREAD

**Issue by leollacer** [NSEE/LPKF#106]
# Sobre :

- Nome do Aluno : leonardo molino llacer
- R.A :14.03930-3
- Habilitação : ca
- Ano : 3
- Nome do Orientador: 
- Nome do Projeto :
- Nome da Disciplina  :

# PCB :

- Nome da Placa :leonardo
- Link para arquivos : 
https://drive.google.com/file/d/0B2pZnbKu4_E6dzExYVF4OV9TaXdscUJxQzZpdFBpamZSLVVn/view?usp=drivesdk
## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (x ) Outro

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa noite Leonardo.
Sua Placa já está pronta.
Renato
