### ISSUE TITLE
César Abraham F. C. Filho - 14.00800-9 - 30/10/2017 - Simples

### ISSUE THREAD

**Issue by Abr4ham** [NSEE/LPKF#107]
# Sobre :

- Nome do Aluno : César Abraham Flores Cisneros Filho
- R.A : 14.00800-9
- Habilitação : Eletrônica
- Ano : 3º Ano
- Nome do Orientador: Valdir Melero Junior
- Nome do Projeto : Fonte Linear Ajustável
- Nome da Disciplina  : Pae - Fontes de Alimentação Lineares

# PCB :

- Nome da Placa : Fonte Linear Ajustável
- Link para arquivos : https://drive.google.com/open?id=0B1dIjMLPlOEQaUhNU2dtbWxZd2s 

## Informações básicas

- Pequeno descritivo sobre a placa : Fonte Linear Ajustável 0-18V 

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (X) Outro - Proteus

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Bom dia César.
Seus gerbers vieram incolpletos.
Não veio o Botom Layer que são as trilhas, nem o board outline. Só chegaram os furos. O restantes dos aquivos que chegaram estão em códigos.
Aguardo contato
Obrigado
Renato

**Comment by Abr4ham** [comment]
Bom dia,
Fiz usando Proteus então usei auxílio da internet para passar pro formato gerber, os layers não ficaram com esses nomes específicos, porém eles estão presentes, selecionando todos e abrindo, com o programa para visualizar gerber descrito no procedimento de envio, pode-se confirmar que todas os layers formam o circuito. 
Atenciosamente,
César Filho

![p_20171104_121520](https://user-images.githubusercontent.com/33226830/32406204-358095e0-c15b-11e7-96a9-7c435b2fdfb0.jpg)

![p_20171104_121530](https://user-images.githubusercontent.com/33226830/32406205-359d93ac-c15b-11e7-9c28-2c85a2607f71.jpg)

![p_20171104_121551](https://user-images.githubusercontent.com/33226830/32406206-35ba6cfc-c15b-11e7-810b-3dfc0f7e2c79.jpg)

![p_20171104_121605](https://user-images.githubusercontent.com/33226830/32406207-35d5961c-c15b-11e7-873c-e40426fb70a4.jpg)

**Comment by Renatolab** [comment]
Boa tarde Cesar.
Sua Placa está pronta
Renato
