### ISSUE TITLE
Lucas Benazzi Cestari - RA 15.00939-4 - Simples

### ISSUE THREAD

**Issue by lucasbenazzi** [NSEE/LPKF#108]
# Sobre :

- Nome do Aluno : Lucas Benazzi Cestari
- R.A : 15.00939-4
- Habilitação : Engenharia Elétrica
- Ano : 3
- Nome do Orientador: Alessandra Dutra Coelho
- Nome do Projeto :
- Nome da Disciplina  : Iniciação Científica

# PCB :

- Nome da Placa : Untitled
- Link para arquivos : https://drive.google.com/open?id=0BwJUiEzBf1YebzJIX0dCb3F0akE

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Bom dia Lucas
Sua Placa está pronta.
Renato
