### ISSUE TITLE
Esteira Seletora_Lucas Ribeiro

### ISSUE THREAD

**Issue by luucasss** [NSEE/LPKF#110]
# Sobre :

- Nome do Aluno : Lucas Ribeiro Gomes
- R.A : 14.03097-7
- Habilitação : CA
- Ano : 3º
- Nome do Orientador: Alessandra
- Nome do Projeto : Estera Seletora
- Nome da Disciplina  : Eletrônica analógica/ digital

# PCB :

- Nome da Placa : Lucas Ribeiro_ Ultiboard
- Link para arquivos : https://drive.google.com/open?id=0ByC9Re_9F7YKblQ3MG9MaDFseXM

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - (x ) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Bom dia Lucas.
Sua Placa está pronta.
Renato
