### ISSUE TITLE
Flyback

### ISSUE THREAD

**Issue by carollinehungaro** [NSEE/LPKF#113]
# Sobre :

- Nome do Aluno :  Carolline de Andrade Hungaro
- R.A : 13.03045-0
- Habilitação : Elétrica
- Ano : 5
- Nome do Orientador: Alessandro
- Nome do Projeto : Flyback
- Nome da Disciplina  : Eletrônica de Potência

# PCB :

- Nome da Placa : Flyback
- Link para arquivos : https://drive.google.com/open?id=1m9SV5SqWuyAswd5wdZOSkRRdjOSTp7mc

## Informações básicas

- Pequeno descritivo sobre a placa : Dupla face somente nos conectores USB, em SMD.

- Software utilizado 
 - (x) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - (x) Dupla Face
 - (x) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa tarde.
Só pra constar registro.
Sua placa está pronta.
Obs: face simples.
Renato
