### ISSUE TITLE
Matheus Jesus - 14.03521-9 - 28/02/2018 - Completa

### ISSUE THREAD

**Issue by mathantunes** [NSEE/LPKF#114]
# Sobre :

- Nome do Aluno : Matheus Antunes de Jesus
- R.A : 14.03521-9
- Habilitação : Eletrônica
- Ano : 5
- Nome do Orientador: Sergio Ribeiro Augusto
- Nome do Projeto : Driver BLDC
- Nome da Disciplina  : CAC 016 - Desenvolvimento de veículos protótipos elétricos de alta eficiência energética

# PCB :

- Nome da Placa : Driver BLDC
- Link para arquivos : [DriverBLDCExport.zip](https://github.com/NSEE/LPKF/files/1768613/DriverBLDCExport.zip)

## Informações básicas

- Pequeno descritivo sobre a placa : Driver de controle de motor brushless utilizado no carro de competição do EcoMauá.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( ) Simples
 - (X) Completa

- Descrição :
 - ( ) Face Simples
 - (X) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara 

[DriverBLDCExport.zip](https://github.com/NSEE/LPKF/files/1768613/DriverBLDCExport.zip)

**Comment by Renatolab** [comment]
Bom dia Matheus.
Sua Placa está pronta.

Renato.
