### ISSUE TITLE
Ronaldo Macarrao - 15.01715-0 - 16/05/2016 - Simples

### ISSUE THREAD

**Issue by ronaldomacarrao** [NSEE/LPKF#13]
# Sobre :
- Nome do Aluno : Ronaldo Macarrao
- R.A :15.01715-0
- Habilitação :Engenharia Eletronica  
- Ano :2º
- Nome do Orientador:Marcio Mathias
- Nome do Projeto : FieldMill
- Nome da Disciplina  :PAE
# PCB :
- Nome da Placa : Fonte fieldmill
- Link para arquivos :https://www.dropbox.com/s/38ekokxdfdfuaiz/fieldmill%20fonte.zip?dl=0
## Informações básicas
- Pequeno descritivo sobre a placa :
- Software utilizado 
  - ( ) Altium
  - ( ) Eagle
  - ( ) Orcad
  - ( x) UltiBoard
  - ( ) Outro
- Tipo de prototipagem
  - (x ) Simples
  - ( ) Completa
- Descrição :
  - (x ) Face Simples
  - ( ) Dupla Face
  - ( ) SMD
  - ( ) Trilha RF
  - ( ) Máscara

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli abri exceção para esse pedido que foi enviado depois da data limite.
obrigado.

**Comment by EvertonFracaroli** [comment]
@corsiferrao ok

**Comment by EvertonFracaroli** [comment]
@ronaldomacarrao a placa esta pronta
