### ISSUE TITLE
Cassio de C. Berni - 27/6/2016 - Completa

### ISSUE THREAD

**Issue by ccberni** [NSEE/LPKF#20]
# Sobre :
- Nome do Aluno : -
- R.A : -
- Habilitação : - 
- Ano : -
- Nome do Orientador: -
- Nome do Projeto : Simucam - Plato
- Nome da Disciplina  : - 
# PCB :
- Nome da Placa : painel_meb
- Link para arquivos : https://dl.dropboxusercontent.com/u/53538635/painel_meb.zip
## Informações básicas
- Pequeno descritivo sobre a placa : Placa de painel para o protótipo do Simucam - NSEE.
- Software utilizado 
  - (x) Altium
  - ( ) Eagle
  - ( ) Orcad
  - ( ) UltiBoard
  - ( ) Outro
- Tipo de prototipagem
  - ( ) Simples
  - (x) Completa
- Descrição :
  - ( ) Face Simples
  - (x) Dupla Face
  - (x) SMD
  - ( ) Trilha RF
  - (x) Máscara

**Comment by EvertonFracaroli** [comment]
@ccberni, Faltou você preencher os seguintes dados. Obrigado, Everton Fracaroli

Nome do Aluno : -
R.A : -
Habilitação : -
Ano : -
Nome do Orientador: -

Nome da Disciplina : -

**Comment by ccberni** [comment]
Olá, Everton, bom dia, tudo bem?
Eu não preenchi esses campos porque não sou aluno, sou bolsista vinculado ao NSEE. Trabalho sob a coordenação dos prof´s Corsi e Vanderlei.
Se precisar de algum dado adicional sobre o projeto, me avise que eu coloco aqui no issue, ok?
Abraço!

**Comment by EvertonFracaroli** [comment]
@ccberni vou esperar uma autorização do @corsiferrao e dar continuidade no processo. obrigado

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli autorizado, essa placa é para o projeto que eu desenvolvo para os europeus. 
obrigado

**Comment by EvertonFracaroli** [comment]
@ccberni estou com uma duvida, na imagem do link coloquei 4 setas em preto, minha duvida é essas parte é algum tipo de encaixe, tenho que retirar essa área da placa? 

https://drive.google.com/drive/folders/0BwoS62oMkZAQbDB2Umg5SXJOa3M

**Comment by ccberni** [comment]
Everton, não estou conseguindo acessar a imagem no google drive, o arquivo não aparece para mim.
Acho que está se referindo aos furos/slots da placa. Temos 4 furos nos cantos, dois furos maiores no interior, para os bnc´s, e 8 slots retangulares. Todos são vazados (sem material de placa), e não metalizados. Veja as faces em 3D, pode ajudar:

https://dl.dropboxusercontent.com/u/53538635/painel_meb_3d.zip

Abs...

**Comment by EvertonFracaroli** [comment]
@ccberni , obrigado era essa minha duvida mesmo

**Comment by EvertonFracaroli** [comment]
@ccberni infelizmente a fresadora entrou em manutenção, você tem pressa para essa placa?

**Comment by ccberni** [comment]
Olá, Everton, creio que não tem problema aguardar. Eu consigo ver outros trabalhos com o Corsi. Você tem uma previsão de quando estaria pronta a placa? Abs...

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli @ccberni essa prototipagem não é mais necessária, prototipamos na griffus.
