### ISSUE TITLE
Guilherme B. Martines - 11.01772-4 - 30/09/2016 - Simples

### ISSUE THREAD

**Issue by guibarsottini** [NSEE/LPKF#21]
# Sobre :
- Nome do Aluno : Guilherme Barsottini Martines
- R.A : 11.01772-4
- Habilitação : Eng Elétrica (Enfase Eletrônica)
- Ano : 5º
- Nome do Orientador: Alessandro Santos 
- Nome do Projeto : Inversor de Freqüência (Tesla)
- Nome da Disciplina  : EEE245 - Eletrônica de Potencia
# PCB :
- Nome da Placa : TESLA
- Link para arquivos : https://drive.google.com/open?id=0B7z5zTwNT1RZT1FmbVJwSmFRb2M
## Informações básicas
- Pequeno descritivo sobre a placa : Driver de controle de uma ponte H com 4 IGBTS.
- Software utilizado 
  - (x) Altium
  - ( ) Eagle
  - ( ) Orcad
  - ( ) UltiBoard
  - ( ) Outro
- Tipo de prototipagem
  - (x) Simples
  - ( ) Completa
- Descrição :
  - (x) Face Simples
  - ( ) Dupla Face
  - ( ) SMD
  - ( ) Trilha RF
  - ( ) Máscara

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli : Favor considerar essa placa do @guibarsottini  para realização do teste da LPKF,

grato !
