### ISSUE TITLE
Guilherme Barsottini - Placa prototipo  -1101772-4

### ISSUE THREAD

**Issue by AmandaViviane** [NSEE/LPKF#24]
# Sobre :
- Nome do Aluno : Guilherme Barsottini 
- R.A : 1101772-4
- Habilitação : Engenharia Eletrônica
- Ano : 5
- Nome do Orientador: Alessandro Santos
- Nome do Projeto : Tesla
- Nome da Disciplina  : Eletrônica de potencia
# PCB :

https://drive.google.com/open?id=0B7I-QIFYgvn8OWJtb1FpNEx4WDg
- Nome da Placa : 
- Link para arquivos : 
## Informações básicas
- Pequeno descritivo sobre a placa :
- Software utilizado 
  - ( x) Altium
  - ( ) Eagle
  - ( ) Orcad
  - ( ) UltiBoard
  - ( ) Outro
- Tipo de prototipagem
  - (x ) Simples
  - ( ) Completa
- Descrição :
  - ( x) Face Simples
  - ( ) Dupla Face
  - (x ) SMD
  - ( ) Trilha RF
  - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta.
