### ISSUE TITLE
Prototipagem

### ISSUE THREAD

**Issue by pedrohzo** [NSEE/LPKF#27]
# Sobre :
- Nome do Aluno : Pedro Henrique Pontes Goncalves 
- R.A : 11.00226-3
- Habilitação : Eletronica
- Ano : 5 
- Nome do Orientador: Jose Carlos de Souza Jr.
- Nome do Projeto : Agripa
- Nome da Disciplina  : -
# PCB :
- Nome da Placa :Gerber Files Mux
  [Gerber Files Mux.zip](https://github.com/NSEE/LPKF/files/540683/Gerber.Files.Mux.zip)
- Link para arquivos : https://drive.google.com/file/d/0B3n3t6DrrzUANTZXWFZCakJfNmc/view?usp=sharing
## Informações básicas
- Pequeno descritivo sobre a placa :
- Software utilizado 
  - (X) Altium
  - ( ) Eagle
  - ( ) Orcad
  - ( ) UltiBoard
  - ( ) Outro
- Tipo de prototipagem
  - (X) Simples
  - ( ) Completa
- Descrição :
  - ( ) Face Simples
  - (X) Dupla Face
  - ( ) SMD
  - ( ) Trilha RF
  - ( ) Máscara

**Comment by pedrohzo** [comment]
Everton, eu mande dupla face pois nao consegui fazer em uma face simples. se houver problema me avise e ai converso contigo para mudar isso. Valeu!

**Comment by EvertonFracaroli** [comment]
@pedrohzo  realmente a maquina não esta fazendo dupla face.

**Comment by pedrohzo** [comment]
Minha placa possui 7 mux 8x1 e um Amp Op gostaria de saber se voce consegue me ajudar para fazer um layout de uma face so

**Comment by EvertonFracaroli** [comment]
@pedrohzo nesse caso tem q fazer alguns jumper

**Comment by pedrohzo** [comment]
@EvertonFracaroli bom dia Everton, atualizei o link do Gerber:
https://drive.google.com/open?id=0B3n3t6DrrzUAcThTbE9MUmFHT0E

Qualquer duvida me liga :972394529

**Comment by EvertonFracaroli** [comment]
Pedro sua placa esta pronta
