### ISSUE TITLE
Matheus Antunes 14.03521-9 - 10/11/16 - Simples

### ISSUE THREAD

**Issue by mathantunes** [NSEE/LPKF#30]
# Sobre :

- Nome do Aluno : Matheus Antunes
- R.A : 14.03521-9
- Habilitação : Engenharia Eletrônica
- Ano : 2016
- Nome do Orientador: 
- Nome do Projeto : Controle de Luminosidade
- Nome da Disciplina  : ETE202

# PCB :

- Nome da Placa : Lamp1
- Link para arquivos : https://drive.google.com/drive/folders/0B9EXYzDan5OWaXAtN2VTSW9xOVE?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa : A partir de controle digital, um sensor de toque aciona uma lâmpada ligada na rede com intensidade controlada

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (x ) Outro
 Proteus
- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - (x) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@mathantunes notei que a sua placa e dupla face nesse caso tem que ter autorização, sua placa não tem plano de terra, nesse caso a gente não retira o excesso de cobre que fica na placa.

**Comment by mathantunes** [comment]
@EvertonFracaroli Atualizei os arquivos, consegui colocar tudo na camada inferior e os limites da placa.

**Comment by rafaelcorsi** [comment]
Ol'a @mathantunes você pode pedir para prototiparmos uma placa dupla face, a única questão é que para isso gastamos muito material e para minimizar desgastes das ferramentas da máquina e do uso de material para metalização utilizamos essa opção realmente quando necessário, mas para isso pedimos a autorização de algum professor responsável pelo projeto.

Verifique o que é melhor para o seu projeto, se quiser continuar na dupla face me passe o nome do Prof. que eu converso com ele para pedir a atuorização.

att,

Prof. R. Corsi

**Comment by EvertonFracaroli** [comment]
@corsiferrao ele conseguiu fazer a placa em face simples, @mathantunes assim que a placa ficar pronta te aviso por esse canal.

**Comment by EvertonFracaroli** [comment]
@mathantunes  a placa esta pronta.
