### ISSUE TITLE
Gerador de corrente

### ISSUE THREAD

**Issue by MAMathias** [NSEE/LPKF#32]
# Sobre :

- Nome do Aluno : 
- R.A :
- Habilitação : 
- Ano : 
- Nome do Orientador: Marcio A Mathias
- Nome do Projeto : Projeto de pesquisa em conjunto com a UNESP-SJC
- Nome da Disciplina  : Pesquisa

# PCB :

- Nome da Placa : Gerador de Corrente
- Link para arquivos : 

- Pequeno descritivo sobre a placa : 
Gerador de corrente de 80 uA para estímulos em pacientes de odontologia

- Software utilizado 
 - ( ) Altium
 - ( x) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@MAMathias Boa Tarde professor, os arquivos que o senhor gerou não estão funcionando. no eagle não sei como faz para gerar os arquivos, sei q as extensões são as seguintes. 

Bottom -> GBL
Top -> GTL
Drill File -> TXT

Att
Everton
