### ISSUE TITLE
Chuveiro Ecológico - 4ºEN - Noturno

### ISSUE THREAD

**Issue by FeMontagneri** [NSEE/LPKF#33]
# Sobre :

- Nome do Aluno : Felipe Antonio Montagneri Lucchini
- R.A : 09,00053-4
- Habilitação :  Eneletrônica
- Ano : 4
- Nome do Orientador: José Carlos
- Nome do Projeto : Chuveiro Ecológico
- Nome da Disciplina  : Projetos em Eletrônica Aplicada

# PCB : 

- Nome da Placa :
- Link para arquivos : https://www.dropbox.com/s/v38rshz0un9e9lc/GERBER.rar?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :

E um protótipo para controle de potencia de um chuveiro.
Se possível retirar todo o cobre não utilizado, e utilizar a maior isolação que der.

- Software utilizado 
 - (x) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - (x) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@FeMontagneri nesse caso por se tratar de uma segunda placa precisa de uma autorização do @corsiferrao.
@FeMontagneri  for informar o motivo pois e a mesma placa que foi feito o pedido da  Amanda Viviane da Costa Fabri R.A : 12.02859-2.

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli @FeMontagneri consultei o Prof. Julio e ele liberou a prototipação ,

corsi

**Comment by FeMontagneri** [comment]
Obrigado!

Obter o Outlook para Android<https://aka.ms/ghei36>



On Tue, Nov 29, 2016 at 4:51 PM -0200, "Rafael Corsi" <notifications@github.com<mailto:notifications@github.com>> wrote:


@EvertonFracaroli<https://github.com/EvertonFracaroli> @FeMontagneri<https://github.com/FeMontagneri> consultei o Prof. Julio e ele liberou a prototipação ,

corsi

-

**Comment by EvertonFracaroli** [comment]
Placa já foi entregue pelo funcionário Renato.
