### ISSUE TITLE
LoRa Radio

### ISSUE THREAD

**Issue by pedrohzo** [NSEE/LPKF#34]
# Sobre :

- Nome do Aluno : Pedro
- R.A : 11.00226-3
- Habilitação : Eng. Eletrônica
- Ano :  5
- Nome do Orientador: Jose carlos de Souza Jr.
- Nome do Projeto : Radio Lora
- Nome da Disciplina  :

# PCB :

- Nome da Placa : Lora
- Link para arquivos : https://drive.google.com/open?id=0B3n3t6DrrzUAVFFQcGpvOTQ0a0k

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( X) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X ) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - ( X) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@pedrohzo tenho uma duvida, notei que tem 3 barramento no meio da placa, porém no aquivo de furação não tem furos para esse barramento é assim mesmo?

**Comment by pedrohzo** [comment]
Vou tentar te mandar de novo. Teria que ter a furação dos barramentos sim. https://drive.google.com/open?id=0B3n3t6DrrzUAVFFQcGpvOTQ0a0k

**Comment by EvertonFracaroli** [comment]
@pedrohzo  esse link já esta com os arquivos atualizados?

**Comment by pedrohzo** [comment]
Sim esta

**Comment by EvertonFracaroli** [comment]
Beleza, vou fazer ela hoje.

**Comment by pedrohzo** [comment]
Valeu Everton! Qualquer coisa me manda mensagem

**Comment by EvertonFracaroli** [comment]
@pedrohzo quando você consegue passar aqui na Mauá? a furação ainda esta incompleta.

**Comment by pedrohzo** [comment]
Eu passo amanhã pode ser ?

**Comment by EvertonFracaroli** [comment]
pode ser sim

**Comment by pedrohzo** [comment]
https://drive.google.com/open?id=0B3n3t6DrrzUAakRCbzlDZGVOYzA

**Comment by pedrohzo** [comment]
Atualizei e amanha o Rafael ira te ligar para conversar. Ve se este esta contendo as marcações! Valeu!!

**Comment by EvertonFracaroli** [comment]
@pedrohzo o funcionário Renato esta de atestado, vou deixar a placa na porta da H227 com um durex, qualquer coisa me liga, 11 995202343.

Att

**Comment by pedrohzo** [comment]
valeu Everton !
