### ISSUE TITLE
Rogério Cassares Pires - 16.83347-3 - 7/3/2017 - Simples

### ISSUE THREAD

**Issue by ghost** [NSEE/LPKF#36]
# Sobre :

# Sobre :

- Nome do Aluno :  Rogério Cassares Pires
- R.A : 16.83347-3
- Habilitação : Engenharia Automotiva
- Ano : 2o
- Nome do Orientador:  William Kurilov
- Nome do Projeto :Placa de velocidade digital Baja
- Nome da Disciplina  :Baja SAE

# PCB :

- Nome da Placa : Mostrador de velocidade e integração de chicote elétrico V1.1
- Link para arquivos : eMAIL

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - (X) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Placa feita e entregue.
