### ISSUE TITLE
Livia Fanucchi - 15.00655-7 - 14/05/2017 - Simples

### ISSUE THREAD

**Issue by LiviaFanucchi** [NSEE/LPKF#40]
# Sobre :

- Nome do Aluno : Livia Zanfelici Fanucchi
- R.A : 15.00655-7
- Habilitação : Controle e Automação 
- Ano : Terceiro Ano
- Nome do Orientador: Professora Alessandra Dutra Coelho
- Nome do Projeto : Projeto Semestral
- Nome da Disciplina  : Eletrônica Digital 

# PCB :

- Nome da Placa : LNR
- Link para arquivos : https://www.dropbox.com/s/xeibzv18tqzvctu/Ultiboard%20Exports.zip?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia Livia, notei que na sua placa tem furação de 0.2mm, eu não tenho essa broca a broca mais proxima que tenho é de 0.6mm, acredito que esses furos são do jumper, em propriedades do furo vc consegue alterar o tamanho da furação. fico no aguardo da atualização do arquivo. 

Att,

Everton Fracaroli
