### ISSUE TITLE
 Frequencímetro

### ISSUE THREAD

**Issue by CaioVinicius100** [NSEE/LPKF#41]
# Sobre :

- Nome do Aluno : Caio Vinicius Goncalves da Silva
- R.A :13.02564-3
- Habilitação : Engenharia de Controle e Automacao
- Ano : 3
- Nome do Orientador: Alessandra Dutra/ Wanderson
- Nome do Projeto :Finalzao
- Nome da Disciplina  : Eletronica Analogica/Digital

# PCB :

- Nome da Placa : Finalzao
- Link para arquivos : https://drive.google.com/drive/folders/0B_btRdas7SieOUhBRWVqdTBiamM?usp=sharing                 ou 
https://www.dropbox.com/s/sfpvmf8u42dsvw9/ProjetoFinalzao.zip?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia Caio, notei que na sua placa tem furação de 0.2mm, eu não tenho essa broca a broca mais proxima que tenho é de 0.6mm, acredito que esses furos são do jumper, em propriedades do furo vc consegue alterar o tamanho da furação. fico no aguardo da atualização do arquivo. 

Att,

Everton Fracaroli
