### ISSUE TITLE
Reenviando da Livia, RA.:15.00655-7

### ISSUE THREAD

**Issue by rtegao** [NSEE/LPKF#42]
# Sobre :

- Nome do Aluno : Ricardo Rossi Tegão
- R.A :14.03795-5
- Habilitação : CA
- Ano : terceiro
- Nome do Orientador: Alessandra/Wandreson
- Nome do Projeto :projeto fim
- Nome da Disciplina  :eletronica analogica/digital

# PCB :

- Nome da Placa :feito
- Link para arquivos : https://drive.google.com/file/d/0B8kVxUUHu1Y4ZTJZSTJ5cGtodFU/view?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - (x ) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@rtegao, a placa esta pronta pode vim retirar.
