### ISSUE TITLE
Reeviando os arquivos de Caio Vinicius 13.02564-3

### ISSUE THREAD

**Issue by CaioVinicius100** [NSEE/LPKF#43]
# Sobre :

- Nome do Aluno : Caio Vinicius Goncalves da Silva
- R.A : 13.02564-3
- Habilitação : CA
- Ano : 3
- Nome do Orientador: Alessandra/Wanderson
- Nome do Projeto :Novo Teste
- Nome da Disciplina  : Eletronica Analogica/Digital

# PCB :

- Nome da Placa : Finalzao
- Link para arquivos : https://drive.google.com/file/d/0B_btRdas7Siea3FOSzVpWHFTTVE/view?usp=sharing 

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x ) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Boa tarde Caio,

Sua placa ainda esta com furação de 0.2mm, quando vc alterar pode só mudar os arquivo no google drive e me avisar.

Att, 

Everton

**Comment by CaioVinicius100** [comment]
Ola Everton, estou deixando aqui o Link para novo arquivo do projeto, eu revisei utilizando o software Gerbv e utilizei na Utilboard no Option -> Global Option -> Jumper size 0.6 mm, e alterou todos os jumpers para 0.6mm, e no software constatou o mesmo.



Link para arquivo ----------> https://drive.google.com/open?id=0B_btRdas7SieVzhsME5HWW1kbTQ

 Me avise que estou em aula, qualquer coisa eu posso conferir com voces.

________________________________
De: EvertonFracaroli <notifications@github.com>
Enviado: segunda-feira, 15 de maio de 2017 17:59
Para: NSEE/LPKF
Cc: CaioVinicius100; Author
Assunto: Re: [NSEE/LPKF] Reeviando os arquivos de Caio Vinicius 13.02564-3 (#43)


Boa tarde Caio,

Sua placa ainda esta com furação de 0.2mm, quando vc alterar pode só mudar os arquivo no google drive e me avisar.

Att,

Everton

**Comment by EvertonFracaroli** [comment]
Caio ainda esta com furos de 0.2mm e sua placa esta fora do tamanho desejado que é de 8 x 10 cm a sua esta com 11 x 14 cm

**Comment by EvertonFracaroli** [comment]
Caio a placa esta pronta
