### ISSUE TITLE
Lucas Benazzi Cestari - 15.00939-4 - 18/05/17

### ISSUE THREAD

**Issue by lucasbenazzi** [NSEE/LPKF#44]
# Sobre : 

- Nome do Aluno : Lucas Benazzi
- R.A : 15.00939-4
- Habilitação : Elétrica
- Ano : 3º
- Nome do Orientador:  Wanderson
- Nome do Projeto : Projeto Semestral de Digitais
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : Placa Digital
- Link para arquivos : https://drive.google.com/open?id=0BwJUiEzBf1YeWmdaaGlyOGxhS0U

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( X) Simples
 - ( ) Completa

- Descrição :
 - ( X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
a placa esta pronta
