### ISSUE TITLE
15.01625-0

### ISSUE THREAD

**Issue by Lucasrozem** [NSEE/LPKF#45]
# Sobre :

- Nome do Aluno : Lucas Rozemberger Duarte
- R.A : 15.01625-0
- Habilitação : Elétrica
- Ano : Terceiro
- Nome do Orientador: Wanderson
- Nome do Projeto : Projeto Semestral
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : LJR
- Link para arquivos : https://drive.google.com/drive/folders/0B1pWSw9eBUiCcF9LRXYxbkJFS3M?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
a placa esta pronta
