### ISSUE TITLE
Guilherme Davanco - 15.00020-6 - 15/05/2017- Simples

### ISSUE THREAD

**Issue by guilhermedavanco** [NSEE/LPKF#51]
# Sobre :

- Nome do Aluno : Guilherme Mucciolo Davanço
- R.A : 15.00020-6
- Habilitação : Eletrônica Noturno
- Ano : Terceiro
- Nome do Orientador: Alessandra Dutra, Alvaro Romanelli
- Nome do Projeto : Projeto Semestral
- Nome da Disciplina  : ETE203, ETE202

# PCB :

- Nome da Placa : teste 01
- Link para arquivos : https://1drv.ms/u/s!An4x37MGuKLC4RH1lRmX2fjKEp82

## Informações básicas

- Pequeno descritivo sobre a placa :
Circuito Eletrônica noturno 2017

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x ) Simples
 - ( ) Completa

- Descrição :
 - (x ) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Sua placa esta pronta, pode ser retirada.
