### ISSUE TITLE
Nemer Chiedde - 15.03515-8 Projeto Semestral

### ISSUE THREAD

**Issue by nemerchiedde** [NSEE/LPKF#52]
# Sobre :

- Nome do Aluno : Nemer Chiedde
- R.A : 15.03515-8
- Habilitação : Elétrica
- Ano : 3°ano
- Nome do Orientador: Wanderson e Alessandra
- Nome do Projeto:  Medidor de Frequência com Sensoriamento Indutivo
- Nome da Disciplina  :Eletrônica Analógica e Digital

# PCB :

- Nome da Placa : Projeto X
- Link para arquivos :

https://www.dropbox.com/sh/rcpg3j9d1bu5ta5/AAC9umAR0boXwQqkIbNHtKWua?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :
Projeto referente as disciplinas Eletrônica Analógica e Digital.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( X ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( X ) Simples
 - ( ) Completa

- Descrição :
 - ( X ) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Sua placa tem furos de 0.2mm provavelmente seja dos jumpers, nesse caso utilizamos a broca de 0.6mm vc pode esta atualizando para essa broca e a placa esta fora do tamanho especificado o tamanho deve ser de 8 c 10 cmm, a sua placa esta com 13 x 11 cm, quando você atualizar os arquivos no dropbox você pode esta enviando uma mensagem pelo github.

Att,

Everton

**Comment by nemerchiedde** [comment]
Olá @EvertonFracaroli,

Alterei o link com o arquivo corrigido.
Obrigado.

Nemer

**Comment by EvertonFracaroli** [comment]
Sua placa esta pronta, pode ser retirada.
