### ISSUE TITLE
Prototipagem

### ISSUE THREAD

**Issue by leonwe** [NSEE/LPKF#53]
# Sobre :

- Nome do Aluno : Leon Cheroto Weissberg
- R.A : 13.01137-5
- Habilitação : CA
- Ano : 3º serie
- Nome do Orientador: Alessandra Dutra
- Nome do Projeto : projeto semestral 1
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : Projeto semestral 1
- Link para arquivos : https://www.dropbox.com/s/2sgi7gxs5ccv04c/projeto%20semetral%201.2%20-%20CADCAM.ZIP?dl=0
## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (X ) Outro

- Tipo de prototipagem
 - (X ) Simples
 - ( ) Completa

- Descrição :
 - ( X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Sua placa tem furos de 0.4mm provavelmente seja dos jumpers, nesse caso utilizamos a broca de 0.6mm vc pode esta atualizando para essa broca e a placa esta fora do tamanho especificado o tamanho deve ser de 8 c 10 cmm, a sua placa esta com 23 x 22 cm, quando você atualizar os arquivos no dropbox você pode esta enviando uma mensagem pelo github.

Att,

Everton

**Comment by leonwe** [comment]
Link atualizado

**Comment by EvertonFracaroli** [comment]
@leonwe na hora que você gerou os arquivos deu alguma coisa errada, fiz um print da tela. segue o link

https://drive.google.com/drive/folders/0BwoS62oMkZAQYTluYmRDMlhuSlU

**Comment by leonwe** [comment]
link atualizado

**Comment by EvertonFracaroli** [comment]
Bom dia a placa esta pronta
