### ISSUE TITLE
Leonardo Faure N Paschoa - 15.01631-5   -  17/05/2017  -  Simples

### ISSUE THREAD

**Issue by leofauree** [NSEE/LPKF#54]
# Sobre :

- Nome do Aluno : Leonardo Faure N Paschoa
- R.A : 15.01631-5
- Habilitação : Engenharia Eletrônica
- Ano : 3o
- Nome do Orientador: Alessandra Dutra
- Nome do Projeto : Frequencímetro Digital
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : Frequencimetro Digital
- Link para arquivos : https://drive.google.com/open?id=0B3hZgoXOTX-0OWg5b0lDMW44WTg

## Informações básicas

- Pequeno descritivo sobre a placa : Projeto de aula

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia a placa esta pronta
