### ISSUE TITLE
João Gustavo C. Soares - 12.00962-8 - 18/05/2017 - Simples

### ISSUE THREAD

**Issue by joaogcs** [NSEE/LPKF#55]
# Sobre :

- Nome do Aluno :  João Gustavo Campos Soares
- R.A : 12.00962-8
- Habilitação : Engenharia de controle e automação 
- Ano :  2017
- Nome do Orientador: Valdir Melero Junior
- Nome do Projeto : Filtro de ruído
- Nome da Disciplina  : ECA407 - Instrumentação

# PCB : 

- Nome da Placa : Filtro de ruído para sensores "sujos"
- Link para arquivos : https://www.dropbox.com/sh/yvi9u3fvxetk07r/AACYf6VlUFAhV44T2jS6jD1Fa?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa : 
A placa contem 2 pontes de Wheatstone, uma para sensores 2 fios (ex.: termopar) e outra para sensores 3 fios (ex.: célula de carga), possui 2 amplificadores, um filtro passa baixa, um filtro passa alta e um filtro para 60hz. O objetivo é conseguir ler os 2 sensores (um de cada vez) fazendo pequenos ajustes nos trimpots. O ganho é de aproximadamente 1000.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (x ) Outro  --> ARES

- Tipo de prototipagem
 - ( x) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia a placa esta pronta
