### ISSUE TITLE
Leonardo M. - 14.03930-3 - 18/5/2017 - Simples

### ISSUE THREAD

**Issue by leollacer** [NSEE/LPKF#57]
# Sobre :

- Nome do Aluno : Leonardo Molino Llacer
- R.A : 14.03930-3
- Habilitação : Engenharia Controle e Automação
- Ano : 3º
- Nome do Orientador:  Alessandra Dutra
- Nome do Projeto : Frequencimetro
- Nome da Disciplina  : Eletrônica Digital

# PCB : 

- Nome da Placa : Lucas
- Link para arquivos :  https://drive.google.com/open?id=0B2pZnbKu4_E6MGcyMzRtd1hIVVE

## Informações básicas
Placa feita para o projeto de eletrônica analogia e eletrônica digital do terceiro ano de controle e automação.

- Pequeno descritivo sobre a placa :
 Placa feita para o projeto de eletrônica analogia e eletrônica digital do terceiro ano de controle e automação.
- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia, 
Seu arquivo de borda esta com 25 x 31cmm e sua trilhas estão finas.

**Comment by leollacer** [comment]
Segue link para correção:
thank you. 
https://1drv.ms/f/s!AswBuWH2XhxEiUYaw5V2nhiCtdd-

**Comment by EvertonFracaroli** [comment]
@leollacer sua borda ainda esta muito grande, se estiver usando o ultiboard seleciona o layer boardoutline, clica na borda em amarelo e que ele vai dar a opção de ajustar a borda.

**Comment by leollacer** [comment]
Olá Everton
O problema já foi corrigido, segue a correção.
https://drive.google.com/open?id=0B2pZnbKu4_E6dm9BT21XX2lWSDQ
Obrigado

**Comment by EvertonFracaroli** [comment]
Bom dia, fiz a sua placa mas ela esta com as trilhas muito finas e muito próxima uma da outra, a maquina fez mas comeu algumas parte das trilha, vou pedir para você deixar mais espaços entre as trilhas e deixar as trilhas mias grosas.

**Comment by leollacer** [comment]
Olá Everton
O problema já foi corrigido, segue a correção.
https://drive.google.com/open?id=0B2pZnbKu4_E6MGcyMzRtd1hIVVE
Obrigado

**Comment by EvertonFracaroli** [comment]
Leonardo sua placa esta com os arquivos certos, porem vou pedir para você diminuir um pouco a borda da placa. Outra coisa notei que você não colocou entrada para alimentação da placa e as saídas do display é isso mesmo?

**Comment by leollacer** [comment]
Everton, bom dia. Não existe a possibilidade de ser feito com esse tamanho de borda ? Pois só conseguimos modificar a noite e precisamos dela para soldar hj e mostrar ao professor se ta ok.

**Comment by leollacer** [comment]
Olá Everton
O problema já foi corrigido, segue a correção.
https://drive.google.com/drive/folders/0B3CpxDT9jeGrOHVXSEtYX05ZOGc
E informando minha dupla vagner também te mandou a correção.

**Comment by EvertonFracaroli** [comment]
Conversei com o renato e ele informou que já fez a entrega da placa.
