### ISSUE TITLE
José Everlando Cordeiro Júnior - 14.01181-6 - 18/05/2017 - Simples

### ISSUE THREAD

**Issue by Josejunior96** [NSEE/LPKF#58]
# Sobre :

- Nome do Aluno : José Everlando Cordeiro Júnior
- R.A : 14.01181-6
- Habilitação : Controle e Automação
- Ano : 3º
- Nome do Orientador: Alessandra Dutra.
- Nome do Projeto : Projeto Semestral 1 - Frequencímetro Digital
- Nome da Disciplina  : Eletrônica Analógica e Eletrônica Digital

# PCB :

- Nome da Placa : Jose_Ultiboard
- Link para arquivos : https://1drv.ms/f/s!AswBuWH2XhxEiVAbrEk4uFZ5eS85
## Informações básicas

- Pequeno descritivo sobre a placa :  Projeto de PCB referente ao Projeto de eletrônica Analógica e Eletrônica digital do curso de Engenharia de Controle e Automação do 3º ano.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia, 

Você precisa gerar os gebers.

**Comment by Josejunior96** [comment]
Boa noite, 
Segue link do arquivo atualizado sem erros de Gebers! 

Muito obrigado!

https://1drv.ms/f/s!AswBuWH2XhxEiUKI1QJvunY4VgIK

**Comment by EvertonFracaroli** [comment]
@Josejunior96 esta faltando o arquivo de borda - **BoardOutline**

**Comment by leollacer** [comment]
Boa tarde @EvertonFracaroli ,  segue link : https://1drv.ms/f/s!AswBuWH2XhxEiUr-zXjsfn2JX-uL 
Espero que dessa vez esteja certo! Obrigado.

**Comment by Josejunior96** [comment]
@EvertonFracaroli , estava logado aqui na máquina como esse @leollacer, mas o arquivo que te enviei é meu @Josejunior96.

**Comment by EvertonFracaroli** [comment]
Bom dia, fiz a sua placa mas ela esta com as trilhas muito finas e muito próxima uma da outra, a maquina fez mas comeu algumas parte das trilha, vou pedir para você deixar mais espaços entre as trilhas e deixar as trilhas mias grosas.

**Comment by Josejunior96** [comment]
Bom dia @EvertonFracaroli, só vou conseguir alterar as trilhas umas 17h, que é o horário que eu chego na Mauá. De qualquer forma, agradeço!

**Comment by Josejunior96** [comment]
Boa noite @EvertonFracarolim, acredito que finalizei o arquivo. Espero que dessa vez dê certo, obrigado! 
https://1drv.ms/f/s!AswBuWH2XhxEiVAbrEk4uFZ5eS85

**Comment by EvertonFracaroli** [comment]
Leonardo sua placa esta com os arquivos certos, porem vou pedir para você diminuir um pouco a borda da placa. Outra coisa notei que você não colocou entrada para alimentação da placa e as saídas do display é isso mesmo?

**Comment by Josejunior96** [comment]
Boa tarde @EvertonFracaroli , segue link atualizado https://1drv.ms/f/s!AswBuWH2XhxEiVag8JBZkGDQRP7r.   Apenas diminui as bordas, porém não alterar entrada, vamos soldar direto. Obrigado!

**Comment by EvertonFracaroli** [comment]
Conversei com o Renato e ele informou que já fez a entrega da placa.
