### ISSUE TITLE
placa de circuito impresso rafael

### ISSUE THREAD

**Issue by psovich123** [NSEE/LPKF#61]
# Sobre : atualizado

- Nome do Aluno :  Rafael Gass
- R.A : 15.03178-0
- Habilitação : controle e automação
- Ano : 3 ano
- Nome do Orientador:  Alessandra Dutra
- Nome do Projeto : projfreq 2
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : projfreq 2
- Link para arquivos : 
https://www.dropbox.com/s/dkfwlkcbclwhmqv/projFreq%202%20-%20CADCAM.ZIP?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (X) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
bom dia, sua placa esta pronta. pode ser retirada na H227

Obrigado
