### ISSUE TITLE
Lucas Benazzi - RA:15.00939-4 - 26/05/2017

### ISSUE THREAD

**Issue by lucasbenazzi** [NSEE/LPKF#62]
# Sobre :

- Nome do Aluno : Lucas Benazzi Cestari
- R.A : 15.00939-4
- Habilitação : Elétrica
- Ano : 2017
- Nome do Orientador: Sérgio
- Nome do Projeto : Projeto Circuitos Analógicos e Digitais
- Nome da Disciplina  : Eletrônica

# PCB :

- Nome da Placa : Placa 2.0
- Link para arquivos : https://drive.google.com/open?id=0BwJUiEzBf1YeaU41X1l1Njd0dTA

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x ) Simples
 - ( ) Completa

- Descrição :
 - ( x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
bom dia, sua placa esta pronta. pode ser retirada na H227

Obrigado
