### ISSUE TITLE
projeto frequencimetro - leon weissberg

### ISSUE THREAD

**Issue by leonwe** [NSEE/LPKF#63]
# Sobre :

- Nome do Aluno : Leon Cheroto Weissberg
- R.A : 13.01137-5
- Habilitação : CA
- Ano : 3º serie
- Nome do Orientador: Alessandra Dutra
- Nome do Projeto : projeto semestral 1
- Nome da Disciplina  : Eletrônica Digital

# PCB :

- Nome da Placa : Projeto semestral 1
- Link para arquivos : 

https://www.dropbox.com/s/fiu7o6p1luurq98/projeto%20semetral%201.2%20-%20CADCAM.ZIP?dl=0

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (X ) Outro

- Tipo de prototipagem
 - (X ) Simples
 - ( ) Completa

- Descrição :
 - ( X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta ponta, pode ser retirada na H227
