### ISSUE TITLE
Daniel Neves Russo - 14.01173-5 - 27/5/2017

### ISSUE THREAD

**Issue by danitos12** [NSEE/LPKF#64]
# Sobre :

- Nome do Aluno : Daniel Neves Russo
- R.A : 14.01173-5
- Habilitação : Engenharia Elétrica
- Ano : 2017
- Nome do Orientador: 
- Nome do Projeto : Eletrônica Analógica - 1 semestre
- Nome da Disciplina  : Eletrônica Analógica

# PCB :

- Nome da Placa : Daniel 14.01173-5
- Link para arquivos : https://drive.google.com/open?id=0B3jZchfrcaZMXy1HaHV2aGJycVU

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Daniel sua placa esta pronta. pode ser retirada na H227.
