### ISSUE TITLE
Pedido 14.02014-9

### ISSUE THREAD

**Issue by nicolasumaras** [NSEE/LPKF#67]
# Sobre :

- Nome do Aluno : Nícolas Rubliauskas Umaras
- R.A : 14.02014-9
- Habilitação : Engenharia Eletrônica
- Ano : 3
- Nome do Orientador:  
- Nome do Projeto : Contador de Frequência
- Nome da Disciplina  : Eletrônica Analógica/Digital

# PCB :

- Nome da Placa : Contador de Frequência
- Link para arquivos : https://drive.google.com/drive/folders/0B3VWuvLS71AQbnN3SThXY2dRZkk?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa : placa com bottom layer, furação para projeto de digital. Segunda placa.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Bom dia, Sua placa esta fora do tamanho padrão para o projeto que e de 8 x 10cm, as trilhas estão finas.
