### ISSUE TITLE
Reenviando Frequencimetro/ Caio Vinicius

### ISSUE THREAD

**Issue by CaioVinicius100** [NSEE/LPKF#69]
# Sobre :

- Nome do Aluno :  Caio Vininicius Goncalves da Silva
- R.A : 13.02564-3
- Habilitação : CA
- Ano : 3
- Nome do Orientador:  Wanderson/Alessandra
- Nome do Projeto : Frequencimetro
- Nome da Disciplina  : Eletronica Analogica/Digital

# PCB :

- Nome da Placa : Tentativa
- Link para arquivos : https://drive.google.com/open?id=0B_btRdas7SiebThLcWltV0pJM2M

## Informações básicas

- Pequeno descritivo sobre a placa : ----- Reenviando a placa por ordem do professor Wanderson, ocorreu curto circuito na placa, nao conseguindo arrumar as soldas e as trilhas, todas as medidas foram aumetadas incluindo os jumpers com 1 mm e as trilhas com 1mm e 0.5 de distancia.------

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta, pode ser retirada na H227
