### ISSUE TITLE
Vitor M. - 14.02147-0 - 03/06/2017 - Simples

### ISSUE THREAD

**Issue by vitormrqs** [NSEE/LPKF#71]
# Sobre :

•	Nome do Aluno : Vitor Marques	
•	R.A : 14.02147-0
•	Habilitação : Controle e Automação
•	Ano : 4 ano
•	Nome do Orientador: Valdir Melero Junior
•	Nome do Projeto : Termômetro
•	Nome da Disciplina : ECA407 - Instrumentação

# PCB :

•	Nome da Placa : Termômetro
•	Link para arquivos : https://drive.google.com/drive/folders/0B9RsJU5yVMRzN3AwVklFT1FsUzQ?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa : A placa possui trilhas para um amplificador, a fim de aumentar o sinal de um termopar tipo K e um filtro de 60 Hz para evitar ruídos da rede.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta, pode ser retirada na H227
