### ISSUE TITLE
Leonardo Henrique Vieira - 14.03898-6 - 06/06/2017 - Simples

### ISSUE THREAD

**Issue by LeoVieiraMaua** [NSEE/LPKF#73]
# Sobre :

- Nome do Aluno : Leonardo Henrique Vieira
- R.A : 14.03898-6
- Habilitação : Engenharia de Controle e Automação
- Ano : 3°
- Nome do Orientador: Alessandra Dutra
- Nome do Projeto : Projeto Semestral 1 - Frequencímetro Digital
- Nome da Disciplina : Eletrônica Analógica / Eletrônica Digital

# PCB :

- Nome da Placa : Leonardo_Andre_Pedro - S1 - PCB
- Link para arquivos : https://drive.google.com/drive/folders/0B8I5asxs4dz6WmotdERqMGp6bWc?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa :   PCB para o Projeto Semestral integrado entre as disciplinas Eletrônica Analógica e Eletrônica Digital (referente ao primeiro semestre de 2017)

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (×) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (×) Simples
 - ( ) Completa

- Descrição :
 - (×) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta, pode ser retirada na H227
