### ISSUE TITLE
Henrique Rosa - 11.02741-0 - 12/6/2017 - Simples FR4 (TOCO PARALELO)

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [NSEE/LPKF#74]
# Sobre : Casador de impedância baseado em toco simples.

- Nome do Aluno : Henrique Pereira Rosa
- R.A : 11.02741-0
- Habilitação : Eletrônica
- Ano : 5º
- Nome do Orientador:  Marcio Mathias
- Nome do Projeto : Projeto final da disciplina
- Nome da Disciplina  : EEN941 - Técnicas em Altas Frequências I

# PCB :

- Nome da Placa : CasadorTocoParalelo.pcbDoc (FR4)
- Link para arquivos :  https://drive.google.com/open?id=0B0FWPGMv9ogrLXJUUGh5MlhfQ2c

## Informações básicas

- Pequeno descritivo sobre a placa :
       Casador de impedância baseado em toco simples.

- Software utilizado 
 - (x) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - (x) Dupla Face (A parte inferior é só um chapado de cobre). 
 - ( ) SMD
 - (x) Trilha RF
 - ( ) Máscara

**Comment by HenriquePereiraRosa** [comment]
@EvertonFracaroli 
Oi Everton. Acho que você fechou esse achando que era a mesma placa, mas esse ISSUE é outra placa. 
E apenas confirmando, também não possui furação.

**Comment by EvertonFracaroli** [comment]
Opa beleza vou ver aqui.

**Comment by HenriquePereiraRosa** [comment]
Valeu!

**Comment by EvertonFracaroli** [comment]
a placa esta pronta.
