### ISSUE TITLE
Henrique Rosa - 11.02741-0 - 12/06/2017 - Simples FR4

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [NSEE/LPKF#75]
# Sobre : Casador de impedância baseado em transformador multiseção (binomial).

- Nome do Aluno : Henrique Pereira Rosa
- R.A : 11.02741-0
- Habilitação : Eletrônica
- Ano : 5º
- Nome do Orientador:  Marcio Mathias
- Nome do Projeto : Projeto final da disciplina
- Nome da Disciplina  : EEN941 - Técnicas em Altas Frequências I

# PCB :
- Nome da Placa : CasadoMultisecaoBinomial.PcbDoc
- Link para arquivos :  https://drive.google.com/open?id=0B0FWPGMv9ogrX2tua0tPZjRaWHc

## Informações básicas

- Pequeno descritivo sobre a placa :
       Casador de impedância baseado em transformador multiseção (binomial).

- Software utilizado 
 - (x) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - (x) Dupla Face (A parte inferior é só um chapado de cobre). 
 - ( ) SMD
 - (x) Trilha RF  (FR4)
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
@HenriquePereiraRosa Essa placa não tem furação mesmo?

**Comment by HenriquePereiraRosa** [comment]
@EvertonFracaroli  
        Isso! sem furação.

**Comment by EvertonFracaroli** [comment]
ok

**Comment by EvertonFracaroli** [comment]
A placa esta pronta

**Comment by HenriquePereiraRosa** [comment]
Valeu!!
