### ISSUE TITLE
Prototipagem placa formula SAE

### ISSUE THREAD

**Issue by ghost** [NSEE/LPKF#76]
# Sobre :

- Nome do Aluno : Gustavo Cassares Pires
- R.A : 14.03037-3
- Habilitação : Controle e automação
- Ano : 4° Diurno
- Nome do Orientador: William Kurilov
- Nome do Projeto : Placa conversora TTL 
- Nome da Disciplina  : Formula SAE

# PCB :

- Nome da Placa : MR17_Telemetry
- Link para arquivos : https://drive.google.com/drive/folders/0ByaZGfsmr9ogMlYxa2d2S24xU2M?usp=sharing

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - (X) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Placa pronta e entregue.
