### ISSUE TITLE
Rogério Cassares Pires. - 16.83347-3- 14/06/2017 - Dupla

### ISSUE THREAD

**Issue by ghost** [NSEE/LPKF#77]
# Sobre :

- Nome do Aluno : Rogério Cassares Pires
- R.A :16.83347-3
- Habilitação : Extracurricular
- Ano : 2017
- Nome do Orientador: Márcio Mathias
- Nome do Projeto : CUBESAT
- Nome da Disciplina  : NSEE

# PCB :

- Nome da Placa :Antena v1.1
- Link para arquivos : enviado por email a everton

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( x) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( ) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - ( x) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta
