### ISSUE TITLE
Everton - 01.010101.01 - 16/5/2016 - Simples

### ISSUE THREAD

**Issue by EvertonFracaroli** [NSEE/LPKF#8]
# Sobre :
- Nome do Aluno : Everton
- R.A : 01.010101.01
- Habilitação :  Elétrica 
- Ano : 01
- Nome do Orientador: Rafael Corsi
- Nome do Projeto : Placa teste
# PCB :
- Nome da Placa : Placa Teste
- Link para arquivos : www.uol.com.br
## Informações básicas
- Pequeno descritivo sobre a placa : placa teste
- Software utilizado 
  - [ ] Altium
  - [ ] Eagle
  - [ ] Orcad
  - [x ] UltiBoard
  - [ ] Outro
- Tipo de prototipagem
  - [ x] Simples
  - [ ] Completa
- Descrição :
  - [ ] Face Simples
  - [ x] Dupla Face
  - [ ] SMD
  - [x ] Trilha RF
  - [ x] Máscara

**Comment by EvertonFracaroli** [comment]
placa teste

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli título fora do padrão

**Comment by rafaelcorsi** [comment]
@EvertonFracaroli 
- [ ] teste
