### ISSUE TITLE
Vinícius Santana - 15.01375-8 - C.A. - 2017 - 01/08/2017

### ISSUE THREAD

**Issue by Viniciusbdsantana** [NSEE/LPKF#81]
# Sobre :

- Nome do Aluno : Vinícius Barbosa de Santana
- R.A : 15.01375-8
- Habilitação : C.A.
- Ano :  2017

# PCB :

- Nome da Placa :
- Link para arquivos : 

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
[blizer2.0 - CADCAM.ZIP](https://github.com/NSEE/LPKF/files/1191575/blizer2.0.-.CADCAM.ZIP)

 - ( ) Orcad
 - ( ) UltiBoard
 - (x) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - ( ) Face Simples
 - (x) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
Esta faltando as seguintes informações

- Nome do Orientador: 
- Nome do Projeto :
- Nome da Disciplina  :
- Pequeno descritivo sobre a placa :

Não precisa abrir outro pedido, pode completar as informações no comentário.

Fico no Aguardo.
