### ISSUE TITLE
Leonardo Diniz - 13.02701-8 - 22/08/2017 - Simples

### ISSUE THREAD

**Issue by LeoDiniz1** [NSEE/LPKF#82]
# Sobre :

- Nome do Aluno : Leonardo Diniz Barbosa
- R.A : 13.02701-8
- Habilitação : Engenharia Controle e Automação
- Ano : 5º Ano
- Nome do Orientador: Rodrigo Romano
- Nome do Projeto : Monitoramento de Transformadores via LoRa
- Nome da Disciplina  : Trabalho de Conclusão de Curso

# PCB :

- Nome da Placa : Timer TCC
- Link para arquivos : https://drive.google.com/open?id=0BzqGqTylQ1Z_ekE2VFV3V1QxR0E

## Informações básicas

- Pequeno descritivo sobre a placa : Um pequeno circuito que irá ligar e desligar um Arduino após um certo período de tempo.

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (x) Outro - Proteus

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by EvertonFracaroli** [comment]
A placa esta pronta pode ser retirada
