### ISSUE TITLE
Henrique Rosa - 11.02741-0 - 11/05/2016 - Simples

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [NSEE/LPKF#9]
# Sobre :
- Nome do Aluno : Henrique Pereira Rosa
- R.A : 11.02741-0
- Habilitação : Engenharia eletrônica
- Ano : 2016
- Nome do Orientador: Rafael Corsi 
- Nome do Projeto : BLDC-Hardware
# PCB :
- Nome da Placa : BLDC.PcbDoc
- Link para arquivos : https://drive.google.com/open?id=0B0FWPGMv9ogrX3NvRWdKZXpQTUU
## Informações básicas
- Pequeno descritivo sobre a placa : Controle de velocidade BLDC
- Software utilizado 
  - [x] Altium
- Tipo de prototipagem
  - [x] Simples
- Descrição :
  - [x] Dupla Face
  - [x] SMD
  - [x] Máscara

**Comment by EvertonFracaroli** [comment]
Boa Tarde @HenriquePereiraRosa, você poderia indicar o caminho exato dos arquivos.

**Comment by HenriquePereiraRosa** [comment]
Boa terde @EvertonFracaroli.

Corrigido: https://drive.google.com/open?id=0B0FWPGMv9ogrX3NvRWdKZXpQTUUXpQTUU

**Comment by EvertonFracaroli** [comment]
@HenriquePereiraRosa o link https://drive.google.com/open?id=0B0FWPGMv9ogrX3NvRWdKZXpQTUUXpQTUU esta dando erro.

**Comment by HenriquePereiraRosa** [comment]
@EvertonFracaroli estou atualizando o link. Mas esqueci de comentar que essa placa simples decidimos não fazer para economizar material. então será feita apenas a completa, tudo bem?

**Comment by EvertonFracaroli** [comment]
@HenriquePereiraRosa  então podemos finalizar esse assunto e finalizar esse chamado?

**Comment by HenriquePereiraRosa** [comment]
@EvertonFracaroli.
Sim, dessa placa simples sim! 
Muito obrigado.
