### ISSUE TITLE
Guilherme Barsottini Martines. - 11.01772-4 - COMPLETA

### ISSUE THREAD

**Issue by guibarsottini** [NSEE/LPKF#91]
# Sobre :

- Nome do Aluno :Guilherme Barsottini Martines 
- R.A :11.01772-4
- Habilitação : Engenharia Eletronica
- Ano : 6º
- Nome do Orientador:Alexsander Tressino 
- Nome do Projeto :Supervisorio Inteligente Para Desagregação Energetica
- Nome da Disciplina  :Trabalho de Conclusão de Curso

# PCB :

- Nome da Placa : Sentinel
- Link para arquivos : https://drive.google.com/open?id=0B7z5zTwNT1RZaEcyVXkxdmYwZTA

## Informações básicas

- Pequeno descritivo sobre a placa : Placa que contem a fonte do projeto e os conversores ADS , se possivel fazer a mesma dupla face metalizada , e aplicar a mascara de Silk.

- Software utilizado 
 - (X) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( ) Simples
 - (X) Completa

- Descrição :
 - ( ) Face Simples
 - (X) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa noite Guilherme.
Sua Placa está pronta.
Renato
