### ISSUE TITLE
Placa TCC Sentinel

### ISSUE THREAD

**Issue by guibarsottini** [NSEE/LPKF#92]
# Sobre :

- Nome do Aluno : Guilherme Barsottini Martines
- R.A :11.01772-4
- Habilitação : Engenharia Eletrica
- Ano : 2017
- Nome do Orientador:Alexsander Tressino 
- Nome do Projeto : Supervisório inteligente para desagregação energética
- Nome da Disciplina  :Trabalho de Conclusão de Curso

# PCB :

- Nome da Placa : Placa de aquisição de dados Sentinel
- Link para arquivos : https://drive.google.com/open?id=0B7z5zTwNT1RZYVdBRk9QTzhyWE0 

## Informações básicas

- Pequeno descritivo sobre a placa : Placa conversora Analog- digital

- Software utilizado 
 - (X) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - ( ) Simples
 - (X) Completa

- Descrição :
 - ( ) Face Simples
 - (X) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa Noite Guilherme.
Sua Placa já esta pronta.
Renato
