### ISSUE TITLE
Lucas Benazzi Cestari - 15.00939-4 - simples

### ISSUE THREAD

**Issue by lucasbenazzi** [NSEE/LPKF#95]
# Sobre :

- Nome do Aluno : Lucas Benazzi Cestari
- R.A : 15.00939-4
- Habilitação : 
- Ano : 3 ano
- Nome do Orientador: Alessandra Dutra Coelho
- Nome do Projeto : Health Care
- Nome da Disciplina  : Iniciação Científica

# PCB :

- Nome da Placa : Untitled
- Link para arquivos : https://drive.google.com/open?id=0BwJUiEzBf1YeRE9uekdXZ1d4R3c

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (x) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (x) Simples
 - ( ) Completa

- Descrição :
 - (x) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Lucas, boa noite.
Sua Placa já está pronta.
Renato
