### ISSUE TITLE
Leonardo Diniz - 13.02701-8 - 22/08/2017

### ISSUE THREAD

**Issue by LeoDiniz1** [NSEE/LPKF#96]
# Sobre :

- Nome do Aluno : Leonardo Diniz Barbosa
- R.A : 13.02701-8
- Habilitação : Engenharia Controle de Automação
- Ano : 5º Ano
- Nome do Orientador: Rodrigo Romano
- Nome do Projeto : Monitoramento de Transformador via LoRa
- Nome da Disciplina  : Trabalho de Conclusão de Curso

# PCB :

- Nome da Placa : Timer TCC
- Link para arquivos : https://drive.google.com/open?id=0BzqGqTylQ1Z_ekE2VFV3V1QxR0E

## Informações básicas

- Pequeno descritivo sobre a placa :

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - ( ) UltiBoard
 - (X) Outro - Proteus

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa Tarde Leonardo
Sua Placa está Pronta
Renato
