### ISSUE TITLE
Vinnicius B. Souza - 15.00437-6 - 24/10/2017 - Simples

### ISSUE THREAD

**Issue by guilhermedavanco** [NSEE/LPKF#97]
# Sobre :

- Nome do Aluno : Vinnicius Bernacchi de Souza
- R.A : 15.00437-6
- Habilitação : Eletrônica noturno
- Ano : 3º
- Nome do Orientador: Alessandra Dutra e Álvaro Romanelli
- Nome do Projeto : Projeto Semestral 2
- Nome da Disciplina  : ETE202 e ETE203

# PCB :

- Nome da Placa : PONTE H
- Link para arquivos : https://mauabr-my.sharepoint.com/personal/15_00437-6_maua_br/_layouts/15/guestaccess.aspx?docid=1cd6a886448d4456bb8a1a7be17303e81&authkey=AfQBRv_PY0C71ldPB4KnKis

## Informações básicas

- Pequeno descritivo sobre a placa : Ponte H

- Software utilizado 
 - ( ) Altium
 - ( ) Eagle
 - ( ) Orcad
 - (X) UltiBoard
 - ( ) Outro

- Tipo de prototipagem
 - (X) Simples
 - ( ) Completa

- Descrição :
 - (X) Face Simples
 - ( ) Dupla Face
 - ( ) SMD
 - ( ) Trilha RF
 - ( ) Máscara

**Comment by Renatolab** [comment]
Boa noite Vinicius.
Sua Placa já está pronta
Renato
